[package]
name = "starfold-preview-nvim"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
starfold-preview-protocol = { version = "0.1", path = "../protocol" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmpv = "1"
crossbeam-channel = "0.5"
starkit = { git = "https://github.com/bstar/starkit", rev = "d52f100f1e787466a99329f6b3eac5908b571d70", version = "0.3", default-features = false }

[dev-dependencies]
tempfile = "3"
proptest = "1"
