[package]
name = "starfold-preview-protocol"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
starkit = { git = "https://github.com/bstar/starkit", rev = "9245a2971ca46d95aec23acc5ab0e643ce849077", version = "0.3", default-features = false }

[dev-dependencies]
proptest = "1"
